//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyMassIndex.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BodyMassIndex.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BMIGroupBox {
            get {
                return ResourceManager.GetString("BMIGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 健康指数：.
        /// </summary>
        internal static string BMILabelCH {
            get {
                return ResourceManager.GetString("BMILabelCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI:.
        /// </summary>
        internal static string BMILabelE {
            get {
                return ResourceManager.GetString("BMILabelE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计算.
        /// </summary>
        internal static string CalculateButtonCH {
            get {
                return ResourceManager.GetString("CalculateButtonCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string CalculateButtonE {
            get {
                return ResourceManager.GetString("CalculateButtonE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 胸围 (cm):.
        /// </summary>
        internal static string ChestLabelCH {
            get {
                return ResourceManager.GetString("ChestLabelCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest (cm):.
        /// </summary>
        internal static string ChestLabelE {
            get {
                return ResourceManager.GetString("ChestLabelE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除.
        /// </summary>
        internal static string ClearButtonCH {
            get {
                return ResourceManager.GetString("ClearButtonCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ClearButtonE {
            get {
                return ResourceManager.GetString("ClearButtonE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 胸围指数:.
        /// </summary>
        internal static string CMILabelCH {
            get {
                return ResourceManager.GetString("CMILabelCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMI:.
        /// </summary>
        internal static string CMILabelE {
            get {
                return ResourceManager.GetString("CMILabelE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 女.
        /// </summary>
        internal static string FemaleRadioButtonCH {
            get {
                return ResourceManager.GetString("FemaleRadioButtonCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string FemaleRadioButtonE {
            get {
                return ResourceManager.GetString("FemaleRadioButtonE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性别.
        /// </summary>
        internal static string GenderGroupBoxCH {
            get {
                return ResourceManager.GetString("GenderGroupBoxCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string GenderGroupBoxE {
            get {
                return ResourceManager.GetString("GenderGroupBoxE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap healthWeightFe {
            get {
                object obj = ResourceManager.GetObject("healthWeightFe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap healthWeightM {
            get {
                object obj = ResourceManager.GetObject("healthWeightM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 身高 (cm):.
        /// </summary>
        internal static string HeightLabelCH {
            get {
                return ResourceManager.GetString("HeightLabelCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (cm):.
        /// </summary>
        internal static string HeightLabelE {
            get {
                return ResourceManager.GetString("HeightLabelE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ico1 {
            get {
                object obj = ResourceManager.GetObject("ico1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico31 {
            get {
                object obj = ResourceManager.GetObject("ico31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        internal static string LanguagesGroupBoxCH {
            get {
                return ResourceManager.GetString("LanguagesGroupBoxCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string LanguagesGroupBoxE {
            get {
                return ResourceManager.GetString("LanguagesGroupBoxE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 男.
        /// </summary>
        internal static string MaleRadioButtonCH {
            get {
                return ResourceManager.GetString("MaleRadioButtonCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string MaleRadioButtonE {
            get {
                return ResourceManager.GetString("MaleRadioButtonE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正常 = 18.5~24.9.
        /// </summary>
        internal static string NormalLabelCH {
            get {
                return ResourceManager.GetString("NormalLabelCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal = 18.5~24.9.
        /// </summary>
        internal static string NormalLabelE {
            get {
                return ResourceManager.GetString("NormalLabelE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap obeseFe {
            get {
                object obj = ResourceManager.GetObject("obeseFe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap obeseM {
            get {
                object obj = ResourceManager.GetObject("obeseM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 肥胖 &gt;=30.
        /// </summary>
        internal static string ObesityLabelCH {
            get {
                return ResourceManager.GetString("ObesityLabelCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obesity &gt;=30.
        /// </summary>
        internal static string ObesityLabelE {
            get {
                return ResourceManager.GetString("ObesityLabelE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap overweightFe {
            get {
                object obj = ResourceManager.GetObject("overweightFe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超重 = 25~29.9.
        /// </summary>
        internal static string OverweightLableCH {
            get {
                return ResourceManager.GetString("OverweightLableCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overweight = 25~29.9.
        /// </summary>
        internal static string OverweightLableE {
            get {
                return ResourceManager.GetString("OverweightLableE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap overweightM {
            get {
                object obj = ResourceManager.GetObject("overweightM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完美: 0.54~0.6.
        /// </summary>
        internal static string PerfectLabelCH {
            get {
                return ResourceManager.GetString("PerfectLabelCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect: 0.54~0.6.
        /// </summary>
        internal static string PerfectLabelE {
            get {
                return ResourceManager.GetString("PerfectLabelE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 偏小:&lt;0.49.
        /// </summary>
        internal static string SamllLabelCH {
            get {
                return ResourceManager.GetString("SamllLabelCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small:&lt;0.49.
        /// </summary>
        internal static string SamllLabelE {
            get {
                return ResourceManager.GetString("SamllLabelE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap skinnyGirl {
            get {
                object obj = ResourceManager.GetObject("skinnyGirl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标准:0.5~0.53.
        /// </summary>
        internal static string StandardLabelCH {
            get {
                return ResourceManager.GetString("StandardLabelCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard:0.5~0.53.
        /// </summary>
        internal static string StandardLabelE {
            get {
                return ResourceManager.GetString("StandardLabelE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 身体健康指数.
        /// </summary>
        internal static string TitleFormCH {
            get {
                return ResourceManager.GetString("TitleFormCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Mass Index.
        /// </summary>
        internal static string TitleFormE {
            get {
                return ResourceManager.GetString("TitleFormE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 太大: &gt;0.6.
        /// </summary>
        internal static string TooBigLabelCH {
            get {
                return ResourceManager.GetString("TooBigLabelCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Big: &gt;0.6.
        /// </summary>
        internal static string TooBigLabelE {
            get {
                return ResourceManager.GetString("TooBigLabelE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap underweightFe {
            get {
                object obj = ResourceManager.GetObject("underweightFe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap underweightM {
            get {
                object obj = ResourceManager.GetObject("underweightM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 偏低 = &lt;18.5.
        /// </summary>
        internal static string UnderwightLabelCH {
            get {
                return ResourceManager.GetString("UnderwightLabelCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underweight = &lt;18.5.
        /// </summary>
        internal static string UnderwightLabelE {
            get {
                return ResourceManager.GetString("UnderwightLabelE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 体重 (kg):.
        /// </summary>
        internal static string WeightLabelCH {
            get {
                return ResourceManager.GetString("WeightLabelCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (kg):.
        /// </summary>
        internal static string WeightLabelE {
            get {
                return ResourceManager.GetString("WeightLabelE", resourceCulture);
            }
        }
    }
}
